<?php 
define("GRID_EDITABLE","EDITABLE");
define("GRID_SVALUE","SVALUE");
define("GRID_EVALUE","EVALUE");
define("GRID_SEQUENCE","SEQUENCE");
define("GRID_ERROR_MESSAGE_FUNCION","ERROR_MESSAGE_FUNCION");
define("GRID_FUNCION","FUNCION");
define("GRID_ERROR_MESSAGE_EXPRESION","ERROR_MESSAGE_EXPRESION");
define("GRID_EXPRESION","EXPRESION");
define("GRID_SELECT","SELECT");
define("GRID_FORCE_ADD_VALUE","FORCE_ADD_VALUE");
define("GRID_FORCE_ADD_VALUE_COMPLEMENT_LEFT","FORCE_ADD_VALUE_COMPLEMENT_LEFT");
define("GRID_FORCE_ADD_VALUE_COMPLEMENT_RIGHT","FORCE_ADD_VALUE_COMPLEMENT_RIGHT");
define("GRID_DISPLAY","DISPLAY");
define("GRID_HIDE_COLUMN","HIDE_COLUMN");
define("GRID_HIDDEN","HIDDEN");
define("GRID_MAX_LENGTH","MAX_LENGTH");
define("GRID","gd");
define("GRID_OR"," OR ");
define("GRID_IN"," IN ");
define("GRID_BETWEEN"," BETWEEN ");
define("GRID_EXPORT_ALL","ALL");
define("GRID_EXPORT_THIS","THIS");
define("GRID_EXPORT_SELECT_ID","GRID_SELECT_EXPORT");
define("GRID_TEMPLATE_SELECT_ID","GRID_SELECT_TEMPLATE");
define("GRID_INPUT_TYPE_PASSWORD","INPUT_TYPE_PASSWORD");
define("GRID_LIMIT_SIZE_EXPORT",99);
define("GRID_LIMIT_SIZE_EXPORT_COLUMN",50);
define("GRIDA000000001","La tabla %s no existe. Codigo de error GRIDA000000001");
define("GRIDA000000002","Error. Codigo de error GRIDA000000002");
define("GRIDA000000003","La(s) tabla(s) no existen. Codigo de error GRIDA000000003");
define("GRIDA000000004","Error registro duplicado");
define("GRIDA000000005","Error al actualizar el registro de la tabla %s");
define("GRIDA000000006","Error al eliminar el registro de la tabla %s");
define("GRIDA000000007","Expresion  logica incorrecta");
define("GRIDA000000008","Session terminada");
define("GRIDA000000009","Error Primary Key de la tabla %s");
define("GRIDA000000010","Error en la transaccion %s");
define("GRIDA000000011","Error en la transaccion GRIDA000000011 SQL");
?>